/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.gpie3k.cron.parser

class App {
    static void main(String[] args) {
        println new Output().format(Parser.parse(args[0]))
    }
}
