/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.gpie3k.cron.parser

import org.gpie3k.cron.parser.output.Output

class App {
    static void main(String[] args) {
        try {
            println Output.format(Parser.parse(args[0]))
        } catch (Exception e) {
            println "ERROR: ${e}"
        }
    }
}
